const appointmentsData = [
    {
        date: '03/03/2024',
        time: '10:00 am',
        service: ['Blindagem'],
        clientName: 'Francisco jr',
        professionalName: 'Maria',
    },
    {
        date: '03/03/2024',
        time: '10:00 am',
        service: ['Blindagem'],
        clientName: 'Francisco jr',
        professionalName: 'Maria',
    },
    {
        date: '03/03/2024',
        time: '10:00 am',
        service: ['Blindagem'],
        clientName: 'Francisco jr',
        professionalName: 'Maria',
    },
    {
        date: '03/03/2024',
        time: '10:00 am',
        service: ['Blindagem'],
        clientName: 'Francisco jr',
        professionalName: 'Maria',
    },
    {
        date: '05/03/2024',
        time: '14:00 pm',
        service: ['Corte de Cabelo'],
        clientName: 'Juliano Bastos',
        professionalName: 'João',
    },
    {
        date: '04/03/2024',
        time: '11:30 am',
        service: ['Barba'],
        clientName: 'Marcos Alan',
        professionalName: 'Pedro',
    },
    {
        date: '04/03/2024',
        time: '15:00 pm',
        service: ['Corte', 'Barba'],
        clientName: 'José Otavio',
        professionalName: 'Ana',
    },
    {
        date: '03/03/2024',
        time: '09:00 am',
        service: ['Corte', 'Barba'],
        clientName: 'Francisco da Silva Dutra',
        professionalName: 'Carlos',
    },
    {
        date: '03/03/2024',
        time: '12:00 pm',
        service: ['Descoloração global'],
        clientName: 'Emanuel Librelotto',
        professionalName: 'Marcela',
    },
    {
        date: '04/03/2024',
        time: '13:30 pm',
        service: ['Barba', 'Corte de Cabelo'],
        clientName: 'Lucas',
        professionalName: 'Renata',
    },
    {
        date: '07/03/2024',
        time: '13:30 pm',
        service: ['Barba', 'Manicure'],
        clientName: 'Lucas',
        professionalName: 'Renata',
    },
    {
        date: '10/03/2024',
        time: '13:30 pm',
        service: ['Barba', 'Depilação'],
        clientName: 'Lucas',
        professionalName: 'Renata',
    },
    {
        date: '14/03/2024',
        time: '13:30 pm',
        service: ['Barba', 'Massagem'],
        clientName: 'Lucas',
        professionalName: 'Renata',
    },
    {
        date: '22/03/2024',
        time: '13:30 pm',
        service: ['Barba', 'Design de Sobrancelhas'],
        clientName: 'Lucas',
        professionalName: 'Renata',
    },
    {
        date: '17/03/2024',
        time: '13:30 pm',
        service: ['Barba', 'Limpeza de Pele'],
        clientName: 'Lucas',
        professionalName: 'Renata',
    },
];
export default appointmentsData;
