const appointmentsData = [
    {
        date: '03/03/2024',
        time: '10:00 am',
        service: [
            'Blindagem',
            'corte de Cabelo',
            'Barba',
            'Limpeza Facial',
            'Botox',
            'corte de Cabelo',
            'Barba',
        ],
        clientName: 'Francisco jr',
        professionalName: 'Eduardo',
    },
    {
        date: '03/03/2024',
        time: '11:00 am',
        service: ['Blindagem', 'Botox', 'corte de Cabelo', 'Barba'],
        clientName: 'Francisco jr',
        professionalName: 'Tereza',
    },
    {
        date: '03/03/2024',
        time: '12:00 pm',
        service: ['Blindagem', 'Design de Sobrancelhas'],
        clientName: 'Francisco jr',
        professionalName: 'João P.',
    },
    {
        date: '03/03/2024',
        time: '01:00 pm',
        service: ['Blindagem'],
        clientName: 'Francisco jr',
        professionalName: 'Maria',
    },
    {
        date: '05/03/2024',
        time: '02:00 pm',
        service: ['Corte de Cabelo'],
        clientName: 'Juliano Bastos',
        professionalName: 'João',
    },
    {
        date: '05/03/2024',
        time: '19:40 pm',
        service: ['Corte de Cabelo'],
        clientName: 'Juliano Bastos',
        professionalName: 'João',
    },
    {
        date: '05/03/2024',
        time: '20:40 pm',
        service: ['Corte de Cabelo'],
        clientName: 'Juliano Bastos',
        professionalName: 'João',
    },
    {
        date: '04/03/2024',
        time: '03:30 pm',
        service: [
            'Barba',
            'Botox',
            'Corte de Cabelo',
            'Design de Sobrancelha',
            'Ventosa Terapia',
            'Degrade navalhado',
            'Pigmentação',
            'Depilação',
        ],
        clientName: 'Marcos Alan',
        professionalName: 'Pedro',
    },
    {
        date: '04/03/2024',
        time: '04:30 pm',
        service: ['Corte de Cabelo', 'Barba', 'Botox'],
        clientName: 'José Otavio',
        professionalName: 'Ana',
    },
    {
        date: '03/03/2024',
        time: '09:00 am',
        service: ['Corte', 'Barba'],
        clientName: 'Francisco da Silva Dutra',
        professionalName: 'Carlos',
    },
    {
        date: '03/03/2024',
        time: '10:00 am',
        service: ['Descoloração global'],
        clientName: 'Emanuel Librelotto',
        professionalName: 'Marcela',
    },
    {
        date: '04/03/2024',
        time: '11:30 am',
        service: ['Barba', 'Corte de Cabelo'],
        clientName: 'Lucas',
        professionalName: 'Renata',
    },
    {
        date: '07/03/2024',
        time: '12:30 pm',
        service: ['Barba', 'Manicure', 'corte de Cabelo'],
        clientName: 'Lucas',
        professionalName: 'Renata',
    },
    {
        date: '10/03/2024',
        time: '01:30 pm',
        service: ['Barba', 'Depilação'],
        clientName: 'Lucas',
        professionalName: 'Renata',
    },
    {
        date: '14/03/2024',
        time: '02:30 pm',
        service: ['Barba', 'Massagem'],
        clientName: 'Lucas',
        professionalName: 'Renata',
    },
    {
        date: '22/03/2024',
        time: '03:30 pm',
        service: ['Barba', 'Design de Sobrancelhas'],
        clientName: 'Lucas',
        professionalName: 'Renata',
    },
    {
        date: '17/03/2024',
        time: '04:30 pm',
        service: ['Barba', 'Limpeza de Pele'],
        clientName: 'Lucas',
        professionalName: 'Renata',
    },
];

export default appointmentsData;
